services:
  app:
    image: yllumi/php83:latest
    volumes:
      - ./public:/var/www/html/public
    networks:
      app-network:
        ipv4_address: 172.20.0.2
    environment:
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html/public
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      app-network:
        ipv4_address: 172.20.0.3

  mariadb:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      app-network:
        ipv4_address: 172.20.0.4

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16