FROM php:8.3-fpm-alpine3.19

WORKDIR /var/www/html

# Install dependencies
RUN apk update && \
    apk add --no-cache \
        freetype \
        libjpeg-turbo \
        libpng \
        libzip \
        icu \
        zlib-dev \
        libzip-dev \
        freetype-dev \
        libjpeg-turbo-dev \
        libpng-dev \
        icu-dev \
        $PHPIZE_DEPS

# Install PHP extensions
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-configure intl \
    && docker-php-ext-install intl \
    && docker-php-ext-install zip \
    && docker-php-ext-install mysqli

# Cleanup unnecessary files
RUN apk del $PHPIZE_DEPS && \
    rm -rf /var/cache/apk/*

CMD ["php-fpm"]
